name: test

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
          ssh-host: allanbraun.net
      - name: Copy files to server
        run: |
          ssh $user@$host "
          rm -rf fontes
          git clone https://github.com/allanvobraun/fontes.git"
        env:
          user: ${{ secrets.DEPLOY_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
      - name: Build
        if: success()
        run: |
          ssh $user@$host "
          cd fontes
          sudo sh ./build.sh
          echo $dotenv >> .env
          ln -sf /home/$user/fontes /var/www/fontes.$host
          "
        env:
          user: ${{ secrets.DEPLOY_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          dotenv: ${{ secrets.ENV_DIGITAL_OCEAN }}



